# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kevin-container-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kevin-container-app
  template:
    metadata:
      labels:
        app: kevin-container-app
    spec:
      containers:
      - name: kevin-container-app
        image: 600627331586.dkr.ecr.us-east-2.amazonaws.com/kevin-container-app:latest
        ports:
        - containerPort: 5000
